version: '3'

services:
  postgres_sql:
    image: postgres:latest
    environment:
      POSTGRES_DB: we-education
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1337
    ports:
      - "5432:5432"
    restart: always
